name = "Aroma1997Core"
filename = "Aroma1997Core-1.12.2-2.0.0.2.b167.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2914/62/Aroma1997Core-1.12.2-2.0.0.2.b167.jar"
hash-format = "murmur2"
hash = "1380001109"

[update]
[update.curseforge]
file-id = 2914062
project-id = 223735
release-channel = "beta"
