name = "Born in a Barn"
filename = "Born In A Barn V1.8-1.12-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2641/661/Born In A Barn V1.8-1.12-1.1.jar"
hash-format = "murmur2"
hash = "3736396456"

[update]
[update.curseforge]
file-id = 2641661
project-id = 285789
release-channel = "beta"
