name = "Building Gadgets"
filename = "BuildingGadgets-2.8.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3005/950/BuildingGadgets-2.8.4.jar"
hash-format = "murmur2"
hash = "1053424356"

[update]
[update.curseforge]
file-id = 3005950
project-id = 298187
release-channel = "beta"
