name = "CC: Tweaked"
filename = "cc-tweaked-1.12.2-1.89.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2992/872/cc-tweaked-1.12.2-1.89.2.jar"
hash-format = "murmur2"
hash = "3991938277"

[update]
[update.curseforge]
file-id = 2992872
project-id = 282001
release-channel = "beta"
