name = "FTB Quests"
filename = "FTBQuests-1202.9.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3077/814/FTBQuests-1202.9.0.13.jar"
hash-format = "murmur2"
hash = "3600649453"

[update]
[update.curseforge]
file-id = 3077814
project-id = 289412
release-channel = "beta"
