name = "Immersive Engineering"
filename = "ImmersiveEngineering-0.12-98.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2974/106/ImmersiveEngineering-0.12-98.jar"
hash-format = "murmur2"
hash = "3177475693"

[update]
[update.curseforge]
file-id = 2974106
project-id = 231951
release-channel = "beta"
