name = "Iron Chests"
filename = "ironchest-1.12.2-7.0.72.847.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2747/935/ironchest-1.12.2-7.0.72.847.jar"
hash-format = "murmur2"
hash = "3272096001"

[update]
[update.curseforge]
file-id = 2747935
project-id = 228756
release-channel = "beta"
