name = "Item Filters"
filename = "ItemFilters-1.0.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3003/364/ItemFilters-1.0.4.2.jar"
hash-format = "murmur2"
hash = "771895873"

[update]
[update.curseforge]
file-id = 3003364
project-id = 309674
release-channel = "beta"
