name = "IvToolkit"
filename = "IvToolkit-1.3.3-1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2443/253/IvToolkit-1.3.3-1.12.jar"
hash-format = "murmur2"
hash = "2463394895"

[update]
[update.curseforge]
file-id = 2443253
project-id = 224535
release-channel = "beta"
