name = "JustEnoughIDs"
filename = "JustEnoughIDs-1.0.3-55.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2919/737/JustEnoughIDs-1.0.3-55.jar"
hash-format = "murmur2"
hash = "2037562781"

[update]
[update.curseforge]
file-id = 2919737
project-id = 296289
release-channel = "beta"
