name = "K4Lib"
filename = "k4lib-1.12.1-2.1.81-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2516/105/k4lib-1.12.1-2.1.81-universal.jar"
hash-format = "murmur2"
hash = "840134802"

[update]
[update.curseforge]
file-id = 2516105
project-id = 224740
release-channel = "beta"
