name = "LibraryEx"
filename = "LibraryEx-1.12.2-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2950/203/LibraryEx-1.12.2-1.1.3.jar"
hash-format = "murmur2"
hash = "1373219563"

[update]
[update.curseforge]
file-id = 2950203
project-id = 298965
release-channel = "beta"
