name = "Mekanism Tools"
filename = "MekanismTools-1.12.2-9.8.3.390.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2835/178/MekanismTools-1.12.2-9.8.3.390.jar"
hash-format = "murmur2"
hash = "644923358"

[update]
[update.curseforge]
file-id = 2835178
project-id = 268567
release-channel = "beta"
