name = "NetherEx"
filename = "NetherEx-1.12.2-2.1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2994/400/NetherEx-1.12.2-2.1.8.jar"
hash-format = "murmur2"
hash = "16973087"

[update]
[update.curseforge]
file-id = 2994400
project-id = 248039
release-channel = "beta"
