name = "Numina"
filename = "Numina-1.12.2-1.0.38.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2715/198/Numina-1.12.2-1.0.38.jar"
hash-format = "murmur2"
hash = "3008756587"

[update]
[update.curseforge]
file-id = 2715198
project-id = 235440
release-channel = "beta"
