name = "Project Intelligence"
filename = "ProjectIntelligence-1.12.2-1.0.9.28-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2833/640/ProjectIntelligence-1.12.2-1.0.9.28-universal.jar"
hash-format = "murmur2"
hash = "585594536"

[update]
[update.curseforge]
file-id = 2833640
project-id = 306028
release-channel = "beta"
