name = "RandomPatches"
filename = "randompatches-1.12.2-1.22.1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3070/895/randompatches-1.12.2-1.22.1.7.jar"
hash-format = "murmur2"
hash = "1283274906"

[update]
[update.curseforge]
file-id = 3070895
project-id = 285612
release-channel = "beta"
