name = "ReAuth"
filename = "reauth-3.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2560/638/reauth-3.6.0.jar"
hash-format = "murmur2"
hash = "1809264525"

[update]
[update.curseforge]
file-id = 2560638
project-id = 237701
release-channel = "beta"
