name = "stimmedcow : NoMoreRecipeConflict"
filename = "NoMoreRecipeConflict-0.13(1.12.2).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2671/230/NoMoreRecipeConflict-0.13(1.12.2).jar"
hash-format = "murmur2"
hash = "3739479058"

[update]
[update.curseforge]
file-id = 2671230
project-id = 238123
release-channel = "beta"
