name = "Traverse: Legacy Continued"
filename = "Traverse-1.12.2-1.6.0-69.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2613/657/Traverse-1.12.2-1.6.0-69.jar"
hash-format = "murmur2"
hash = "2645941718"

[update]
[update.curseforge]
file-id = 2613657
project-id = 267769
release-channel = "beta"
