name = "VanillaFix"
filename = "VanillaFix-1.0.10-150.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2915/154/VanillaFix-1.0.10-150.jar"
hash-format = "murmur2"
hash = "2608670190"

[update]
[update.curseforge]
file-id = 2915154
project-id = 292785
release-channel = "beta"
