name = "WanionLib"
filename = "WanionLib-1.12.2-2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3064/112/WanionLib-1.12.2-2.5.jar"
hash-format = "murmur2"
hash = "3692313526"

[update]
[update.curseforge]
file-id = 3064112
project-id = 253043
release-channel = "beta"
