name = "ZeroCore 2"
filename = "zerocore-1.12.2-0.1.2.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2670/570/zerocore-1.12.2-0.1.2.8.jar"
hash-format = "murmur2"
hash = "3964756235"

[update]
[update.curseforge]
file-id = 2670570
project-id = 247921
release-channel = "beta"
