name = "Colossal Chests"
filename = "ColossalChests-1.12.2-1.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2718/588/ColossalChests-1.12.2-1.7.3.jar"
hash-format = "murmur2"
hash = "357764832"

[update]
[update.curseforge]
file-id = 2718588
project-id = 237875
release-channel = "beta"
