name = "Controlling"
filename = "Controlling-3.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3025/548/Controlling-3.0.10.jar"
hash-format = "murmur2"
hash = "2077870799"

[update]
[update.curseforge]
file-id = 3025548
project-id = 250398
release-channel = "beta"
