name = "CoroUtil"
filename = "coroutil-1.12.1-1.2.37.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2902/920/coroutil-1.12.1-1.2.37.jar"
hash-format = "murmur2"
hash = "2316559879"

[update]
[update.curseforge]
file-id = 2902920
project-id = 237749
release-channel = "beta"
