name = "Cucumber Library"
filename = "Cucumber-1.12.2-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2645/867/Cucumber-1.12.2-1.1.3.jar"
hash-format = "murmur2"
hash = "3550059760"

[update]
[update.curseforge]
file-id = 2645867
project-id = 272335
release-channel = "beta"
