name = "Custom Main Menu"
filename = "CustomMainMenu-MC1.12.2-2.0.9.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2857/869/CustomMainMenu-MC1.12.2-2.0.9.1.jar"
hash-format = "murmur2"
hash = "3526146934"

[update]
[update.curseforge]
file-id = 2857869
project-id = 226406
release-channel = "beta"
