name = "/dank/null"
filename = "DankNull-1.12.2-1.7.101.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2962/52/DankNull-1.12.2-1.7.101.jar"
hash-format = "murmur2"
hash = "4017976554"

[update]
[update.curseforge]
file-id = 2962052
project-id = 272514
release-channel = "beta"
