name = "Extreme Reactors 2"
filename = "ExtremeReactors-1.12.2-0.4.5.67.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2722/271/ExtremeReactors-1.12.2-0.4.5.67.jar"
hash-format = "murmur2"
hash = "2732073367"

[update]
[update.curseforge]
file-id = 2722271
project-id = 250277
release-channel = "beta"
