name = "Just Enough Items (JEI)"
filename = "jei_1.12.2-4.16.1.301.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3040/523/jei_1.12.2-4.16.1.301.jar"
hash-format = "murmur2"
hash = "3089143260"

[update]
[update.curseforge]
file-id = 3040523
project-id = 238222
release-channel = "beta"
