name = "Modular Powersuits"
filename = "ModularPowersuits-1.12.2-1.0.46.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2743/885/ModularPowersuits-1.12.2-1.0.46.jar"
hash-format = "murmur2"
hash = "1198111134"

[update]
[update.curseforge]
file-id = 2743885
project-id = 235442
release-channel = "beta"
