name = "ToroHealth Damage Indicators"
filename = "torohealth-1.12.2-11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2483/817/torohealth-1.12.2-11.jar"
hash-format = "murmur2"
hash = "378881515"

[update]
[update.curseforge]
file-id = 2483817
project-id = 245733
release-channel = "beta"
