name = "WorldEdit"
filename = "worldedit-forge-mc1.12.2-6.1.10-dist.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2941/712/worldedit-forge-mc1.12.2-6.1.10-dist.jar"
hash-format = "murmur2"
hash = "198975533"

[update]
[update.curseforge]
file-id = 2941712
project-id = 225608
release-channel = "beta"
